DATASET:
  TRAIN: "coco_2014_train_simple"
  VAL: "coco_2014_val_online"
  TEST: "coco_2014_test_online"
  VOCAB_PATH: "G:/PyProjects/image_captioning_universal/datasets/coco/vocab.pkl"
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  MAX_ITER: 40000
  OPTIMIZER: "Adam"
  SCHEDULER: "StepLR"
  STEP_SIZE: 3500
  GAMMA: 0.8
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.00001
  IMS_PER_BATCH: 8
  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 10000
  VAL_PERIOD: 2000
  SCST_AFTER: 20000
  METRIC_LOGGER_NAME: "resnet_topdown_ce"
MODEL:
  DECODER:
    BEAM_SIZE: 1
    ARCH: "TopDown"
TEST:
  IMS_PER_BATCH: 8
  BEAM_SIZE: 3
OUTPUT_DIR: "save/resnet_topdown_ce"

